package br.com.projeto.edutech.interface_grafica;

import javax.swing.*;
import java.awt.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author JoÃ£o Gabriel Nascimento
 */
public class InterfacePrincipal extends JFrame {

    private String nomeNovaSerie;
    private int episodiosNovaSerie;

    /**
     * Creates new form InterfacePrincipal
     */
    public InterfacePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Nome = new JLabel();
        Titulo = new JLabel();
        Situacao = new JLabel();
        Episodios = new JLabel();
        TemporadasSagas = new JLabel();

        PainelTitulo = new JPanel();
        Gerenciamento = new JPanel();

        NomeCampo = new JTextField();
        EpisodiosCampo = new JTextField();
        TemporadasSagasCampo = new JTextField();

        Adicionar = new JButton();

        Retomar = new JRadioButton();
        Assistirei = new JRadioButton();
        Assistindo = new JRadioButton();
        Terminado = new JRadioButton();

        BotoesSituacao = new ButtonGroup();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Organizador de Séries");
        setLocation(new Point(800, 400));
        setResizable(false);

        Nome.setFont(new Font("Arial", Font.BOLD, 18)); // NOI18N
        Nome.setText("Nome:");

        TemporadasSagas.setFont(new Font("Arial", Font.BOLD, 18)); // NOI18N
        TemporadasSagas.setText("Temporadas:");

        Episodios.setFont(new Font("Arial", Font.BOLD, 18)); // NOI18N
        Episodios.setText("Episódios:");

        Situacao.setFont(new Font("Arial", Font.BOLD, 18)); // NOI18N
        Situacao.setText("Situação:");

        BotoesSituacao.add(Assistirei);
        Assistirei.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        Assistirei.setText("Assistirei");

        BotoesSituacao.add(Assistindo);
        Assistindo.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        Assistindo.setText("Assistindo");

        BotoesSituacao.add(Retomar);
        Retomar.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        Retomar.setText("Retomar");

        BotoesSituacao.add(Terminado);
        Terminado.setFont(new Font("Arial", Font.PLAIN, 14)); // NOI18N
        Terminado.setText("Terminado");

        Adicionar.setFont(new Font("Arial", Font.PLAIN, 24)); // NOI18N
        Adicionar.setText("Adicionar");
        Adicionar.setMaximumSize(new Dimension(70, 37));
        Adicionar.setMinimumSize(new Dimension(70, 37));
        Adicionar.setPreferredSize(new Dimension(70, 37));

        GroupLayout GerenciamentoLayout = new GroupLayout(Gerenciamento);
        Gerenciamento.setLayout(GerenciamentoLayout);
        GerenciamentoLayout.setHorizontalGroup(
            GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GerenciamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Adicionar, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(GroupLayout.Alignment.LEADING, GerenciamentoLayout.createSequentialGroup()
                        .addComponent(Nome)
                        .addGap(18, 18, 18)
                        .addComponent(NomeCampo))
                    .addGroup(GroupLayout.Alignment.LEADING, GerenciamentoLayout.createSequentialGroup()
                        .addComponent(TemporadasSagas)
                        .addGap(18, 18, 18)
                        .addComponent(TemporadasSagasCampo))
                    .addGroup(GroupLayout.Alignment.LEADING, GerenciamentoLayout.createSequentialGroup()
                        .addComponent(Episodios)
                        .addGap(18, 18, 18)
                        .addComponent(EpisodiosCampo))
                    .addGroup(GroupLayout.Alignment.LEADING, GerenciamentoLayout.createSequentialGroup()
                        .addComponent(Situacao)
                        .addGap(18, 18, 18)
                        .addComponent(Assistirei)
                        .addGap(18, 18, 18)
                        .addComponent(Assistindo)
                        .addGap(18, 18, 18)
                        .addComponent(Retomar)
                        .addGap(20, 20, 20)
                        .addComponent(Terminado)))
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        GerenciamentoLayout.setVerticalGroup(
            GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GerenciamentoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Nome)
                    .addComponent(NomeCampo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(TemporadasSagas)
                    .addComponent(TemporadasSagasCampo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Episodios)
                    .addComponent(EpisodiosCampo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(GerenciamentoLayout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Assistirei)
                    .addComponent(Assistindo)
                    .addComponent(Situacao)
                    .addComponent(Retomar)
                    .addComponent(Terminado))
                .addGap(18, 18, 18)
                .addComponent(Adicionar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(156, Short.MAX_VALUE))
        );

        Titulo.setFont(new Font("Arial", Font.BOLD, 48)); // NOI18N
        Titulo.setHorizontalAlignment(SwingConstants.CENTER);
        Titulo.setText("Gerenciador de Séries");

        GroupLayout PainelTituloLayout = new GroupLayout(PainelTitulo);
        PainelTitulo.setLayout(PainelTituloLayout);

        PainelTituloLayout.setHorizontalGroup(
            PainelTituloLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(PainelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        PainelTituloLayout.setVerticalGroup(
            PainelTituloLayout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(PainelTituloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo, GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(PainelTitulo, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Gerenciamento, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PainelTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(Gerenciamento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (UIManager.LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | UnsupportedLookAndFeelException | IllegalAccessException | InstantiationException ex) {
            Logger.getLogger(InterfacePrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfacePrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private ButtonGroup BotoesSituacao;
    private JButton Adicionar;

    private JRadioButton Retomar;
    private JRadioButton Terminado;
    private JRadioButton Assistindo;
    private JRadioButton Assistirei;

    private JTextField NomeCampo;
    private JTextField EpisodiosCampo;

    private JPanel PainelTitulo;
    private JPanel Gerenciamento;

    private JLabel Nome;
    private JLabel Titulo;
    private JLabel Situacao;
    private JLabel Episodios;
    private JLabel TemporadasSagas;

    private JTextField TemporadasSagasCampo;
    // End of variables declaration//GEN-END:variables
}
